INSERT INTO countries (name) VALUES
('United States'),
('Canada'),
('Mexico'),
('Brazil'),
('Argentina'),
('United Kingdom'),
('Germany'),
('France'),
('Spain'),
('Italy'),
('Portugal'),
('Netherlands'),
('Belgium'),
('Switzerland'),
('Austria'),
('Sweden'),
('Norway'),
('Denmark'),
('Finland'),
('Poland'),
('Russia'),
('Ukraine'),
('Turkey'),
('Greece'),
('Egypt'),
('South Africa'),
('Nigeria'),
('Kenya'),
('Morocco'),
('Japan'),
('China'),
('India'),
('South Korea'),
('Australia'),
('New Zealand'),
('Singapore'),
('Malaysia'),
('Indonesia'),
('Thailand'),
('Vietnam'),
('Philippines'),
('Saudi Arabia'),
('United Arab Emirates'),
('Israel'),
('Iran'),
('Iraq'),
('Chile'),
('Colombia'),
('Peru'),
('Venezuela');