INSERT INTO people (name, birthdate, bio, photo_url) VALUES
('Tom Hanks', '1956-07-09', 'American actor and filmmaker.', 'https://i.imgur.com/people1.png'),
('Meryl Streep', '1949-06-22', 'American actress. Often described as the "best actress of her generation".', 'https://i.imgur.com/people2.png'),
('Leonardo DiCaprio', '1974-11-11', 'American actor and film producer.', NULL),
('Scarlett Johansson', '1984-11-22', 'American actress and singer.', 'https://i.imgur.com/people4.png'),
('Robert De Niro', '1943-08-17', 'American actor, producer, and director.', 'https://i.imgur.com/people5.png'),
('Christopher Nolan', '1970-07-30', 'British-American film director, producer, and screenwriter.', NULL),
('Quentin Tarantino', '1963-03-27', 'American film director, screenwriter, producer, and actor.', 'https://i.imgur.com/people7.png'),
('Martin Scorsese', '1942-11-17', 'American film director, producer, screenwriter, and actor.', 'https://i.imgur.com/people8.png'),
('Morgan Freeman', '1937-06-01', 'American actor and narrator.', 'https://i.imgur.com/people9.png'),
('Brad Pitt', '1963-12-18', 'American actor and film producer.', NULL),
('Angelina Jolie', '1975-06-04', 'American actress, filmmaker, and humanitarian.', 'https://i.imgur.com/people11.png'),
('Denzel Washington', '1954-12-28', 'American actor, director, and producer.', 'https://i.imgur.com/people12.png'),
('Anthony Hopkins', '1937-12-31', 'Welsh actor, director, and producer.', 'https://i.imgur.com/people13.png'),
('Keanu Reeves', '1964-09-02', 'Canadian actor.', 'https://i.imgur.com/people14.png'),
('Natalie Portman', '1981-06-09', 'Israeli-American actress.', NULL),
('Christian Bale', '1974-01-30', 'English actor.', 'https://i.imgur.com/people16.png'),
('Cillian Murphy', '1976-05-25', 'Irish actor.', 'https://i.imgur.com/people17.png'),
('Margot Robbie', '1990-07-02', 'Australian actress and producer.', 'https://i.imgur.com/people18.png'),
('Ryan Gosling', '1980-11-12', 'Canadian actor.', 'https://i.imgur.com/people19.png'),
('Emma Stone', '1988-11-06', 'American actress.', NULL),
('Jennifer Lawrence', '1990-08-15', 'American actress.', 'https://i.imgur.com/people21.png'),
('Matt Damon', '1970-10-08', 'American actor, producer, and screenwriter.', 'https://i.imgur.com/people22.png'),
('Zendaya', '1996-09-01', 'American actress and singer.', 'https://i.imgur.com/people23.png'),
('Timothée Chalamet', '1995-12-27', 'American and French actor.', 'https://i.imgur.com/people24.png'),
('Anya Taylor-Joy', '1996-04-16', 'American-born Argentine-British actress.', 'https://i.imgur.com/people25.png'),
('Steven Spielberg', '1946-12-18', 'American film director, producer, and screenwriter.', NULL),
('Greta Gerwig', '1983-08-04', 'American actress, screenwriter, and director.', 'https://i.imgur.com/people27.png'),
('Denis Villeneuve', '1967-10-03', 'Canadian film director, producer, and screenwriter.', 'https://i.imgur.com/people28.png'),
('Bong Joon-ho', '1969-09-14', 'South Korean film director and screenwriter.', 'https://i.imgur.com/people29.png'),
('Idris Elba', '1972-09-06', 'English actor.', 'https://i.imgur.com/people30.png'),
('Chris Hemsworth', '1983-08-11', 'Australian actor.', NULL),
('Tom Holland', '1996-06-01', 'English actor.', 'https://i.imgur.com/people32.png'),
('Millie Bobby Brown', '2004-02-19', 'British actress.', 'https://i.imgur.com/people33.png'),
('Henry Cavill', '1983-05-05', 'British actor.', 'https://i.imgur.com/people34.png'),
('Pedro Pascal', '1975-04-02', 'Chilean and American actor.', 'https://i.imgur.com/people35.png'),
('Jenna Ortega', '2002-09-27', 'American actress.', 'https://i.imgur.com/people36.png'),
('Olivia Colman', '1974-01-30', 'English actress.', 'https://i.imgur.com/people37.png'),
('Bryan Cranston', '1956-03-07', 'American actor and filmmaker.', 'https://i.imgur.com/people38.png'),
('Aaron Paul', '1979-08-27', 'American actor.', 'https://i.imgur.com/people39.png'),
('Peter Dinklage', '1969-06-11', 'American actor.', 'https://i.imgur.com/people40.png'),
('Emilia Clarke', '1986-10-23', 'English actress.', NULL),
('Kit Harington', '1986-12-26', 'English actor.', 'https://i.imgur.com/people42.png'),
('Jason Bateman', '1969-01-14', 'American actor, director, and producer.', 'https://i.imgur.com/people43.png'),
('Jennifer Aniston', '1969-02-11', 'American actress.', 'https://i.imgur.com/people44.png'),
('Steve Carell', '1962-08-16', 'American actor and comedian.', 'https://i.imgur.com/people45.png'),
('Adam Sandler', '1966-09-09', 'American comedian, actor, and filmmaker.', 'httpsa://i.imgur.com/people46.png'),
('Dwayne Johnson', '1972-05-02', 'American actor and former professional wrestler.', 'https://i.imgur.com/people47.png'),
('Will Smith', '1968-09-25', 'American actor, rapper, and producer.', NULL),
('Keira Knightley', '1985-03-26', 'English actress.', 'https://i.imgur.com/people49.png'),
('Florence Pugh', '1996-01-03', 'English actress.', 'https://i.imgur.com/people50.png');