INSERT INTO profiles (user_id, profile_name, maturity_rating, avatar_url) VALUES

(1, 'User One', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(2, 'User Two', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(3, 'User Three', 'ALL', NULL),
(4, 'User Four', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(5, 'User Five', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(6, 'User Six', 'ALL', NULL),
(7, 'User Seven', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(8, 'User Eight', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(9, 'User Nine', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(10, 'User Ten', 'ALL', NULL),
(11, 'User Eleven', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(12, 'User Twelve', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(13, 'User Thirteen', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(14, 'User Fourteen', 'ALL', NULL),
(15, 'User Fifteen', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(16, 'User Sixteen', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(17, 'User Seventeen', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(18, 'User Eighteen', 'ALL', NULL),
(19, 'User Nineteen', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(20, 'User Twenty', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(21, 'User TwentyOne', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(22, 'User TwentyTwo', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(23, 'User TwentyThree', 'ALL', NULL),
(24, 'User TwentyFour', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(25, 'User TwentyFive', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(26, 'User TwentySix', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(27, 'User TwentySeven', 'ALL', NULL),
(28, 'User TwentyEight', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(29, 'User TwentyNine', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(30, 'User Thirty', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(31, 'User ThirtyOne', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(32, 'User ThirtyTwo', 'ALL', NULL),
(33, 'User ThirtyThree', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(34, 'User ThirtyFour', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(35, 'User ThirtyFive', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(36, 'User ThirtySix', 'ALL', NULL),
(37, 'User ThirtySeven', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(38, 'User ThirtyEight', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(39, 'User ThirtyNine', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(40, 'User Forty', 'ALL', NULL),
(41, 'User FortyOne', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(42, 'User FortyTwo', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(43, 'User FortyThree', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(44, 'User FortyFour', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(45, 'User FortyFive', 'ALL', NULL),
(46, 'User FortySix', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(47, 'User FortySeven', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(48, 'User FortyEight', 'ALL', 'https://i.imgur.com/avatar_default.png'),
(49, 'User FortyNine', 'ALL', NULL),
(50, 'User Fifty', 'ALL', 'https://i.imgur.com/avatar_default.png'),

(1, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(2, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(3, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(4, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(5, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(6, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(7, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(8, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(9, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(10, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(11, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(12, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(13, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(14, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(15, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(16, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(17, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(18, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(19, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(20, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(21, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(22, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(23, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(24, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(25, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(26, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(27, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(28, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(29, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(30, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(31, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(32, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(33, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(34, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(35, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(36, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(37, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(38, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(39, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(40, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(41, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(42, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(43, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(44, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(45, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(46, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(47, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(48, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(49, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png'),
(50, 'Kids', 'KIDS', 'https://i.imgur.com/avatar_kids.png');