INSERT INTO titles (type, original_title, synopsis, release_year, age_rating, poster_url, backdrop_url) VALUES

('MOVIE', 'The Great Adventure', 'A thrilling synopsis of an adventure across mountains and seas.', 2023, '12', 'https://i.imgur.com/poster1.png', 'https://i.imgur.com/backdrop1.png'),
('MOVIE', 'Space Odyssey 2049', 'A sci-fi journey to the edge of the universe. A true mystery.', 2022, '14', 'https://i.imgur.com/poster2.png', NULL),
('MOVIE', 'Midnight Shadows', 'A noir mystery set in a city that never sleeps. Full of action.', 2021, '16', NULL, 'https://i.imgur.com/backdrop3.png'),
('MOVIE', 'Comedy Central Live', 'The funniest comedy show of the year.', 2024, '10', 'https://i.imgur.com/poster4.png', 'https://i.imgur.com/backdrop4.png'),
('MOVIE', 'The Last Stand', 'A story of survival and action. A true drama.', 2020, '18', 'https://i.imgur.com/poster5.png', NULL),
('MOVIE', 'Forgotten Kingdom', 'A fantasy epic about a lost kingdom and a great adventure.', 2019, '12', 'https://i.imgur.com/poster6.png', 'https://i.imgur.com/backdrop6.png'),
('MOVIE', 'Quantum Leap', 'A scientist discovers time travel in this sci-fi tale.', 2023, '14', NULL, NULL),
('MOVIE', 'Heartbeats', 'A touching drama about love and loss.', 2022, 'L', 'https://i.imgur.com/poster8.png', 'https://i.imgur.com/backdrop8.png'),
('MOVIE', 'The Spy Game', 'An action-packed thriller with a spy mystery.', 2021, '16', 'https://i.imgur.com/poster9.png', NULL),
('MOVIE', 'Wild Planet', 'A documentary exploring the amazing wildlife of our planet.', 2024, 'L', 'https://i.imgur.com/poster10.png', 'https://i.imgur.com/backdrop10.png'),
('MOVIE', 'Crimson Peak', 'A haunting horror story set in an isolated mansion.', 2018, '18', NULL, 'https://i.imgur.com/backdrop11.png'),
('MOVIE', 'The Chef', 'A comedy about a chef who loses his restaurant and starts a food truck.', 2017, '10', 'https://i.imgur.com/poster12.png', 'https://i.imgur.com/backdrop12.png'),
('MOVIE', 'Ocean''s Deep', 'A sci-fi mystery unfolds in the deep ocean.', 2022, '14', 'https://i.imgur.com/poster13.png', NULL),
('MOVIE', 'The Racer', 'An adrenaline-fueled action movie about a Formula 1 driver.', 2023, '12', 'https://i.imgur.com/poster14.png', 'https://i.imgur.com/backdrop14.png'),
('MOVIE', 'War Path', 'A gritty drama about soldiers on the front line.', 2019, '18', NULL, NULL),
('MOVIE', 'Cyber City', 'In a futuristic city, a detective hunts a robot in this sci-fi thriller.', 2025, '16', 'https://i.imgur.com/poster16.png', 'https://i.imgur.com/backdrop16.png'),
('MOVIE', 'Love in Paris', 'A classic romantic comedy set in the city of love.', 2016, '10', 'https://i.imgur.com/poster17.png', NULL),
('MOVIE', 'The Heist', 'A crew plans the biggest bank heist in history. Pure action.', 2021, '16', 'https://i.imgur.com/poster18.png', 'https://i.imgur.com/backdrop18.png'),
('MOVIE', 'Ghost Town', 'A western with a supernatural mystery.', 2020, '14', NULL, 'https://i.imgur.com/backdrop19.png'),
('MOVIE', 'King''s Gambit', 'A historical drama about a king''s difficult choice.', 2022, '12', 'https://i.imgur.com/poster20.png', 'https://i.imgur.com/backdrop20.png'),
('MOVIE', 'Project Gemini', 'A top-secret sci-fi project goes wrong.', 2023, '14', 'https://i.imgur.com/poster21.png', NULL),
('MOVIE', 'Sunset Boulevard', 'A classic noir film about a faded star.', 1950, '14', 'https://i.imgur.com/poster22.png', 'https://i.imgur.com/backdrop22.png'),
('MOVIE', 'The Code', 'A programmer finds a dangerous secret. A digital thriller.', 2024, '16', NULL, NULL),
('MOVIE', 'Mountain High', 'An adventure documentary about climbers.', 2021, 'L', 'https://i.imgur.com/poster24.png', 'https://i.imgur.com/backdrop24.png'),
('MOVIE', 'Silent Scream', 'A terrifying horror movie where silence is survival.', 2023, '18', 'https://i.imgur.com/poster25.png', NULL),
('MOVIE', 'The Artist', 'A drama about a painter struggling for recognition.', 2018, '12', 'https://i.imgur.com/poster26.png', 'https://i.imgur.com/backdrop26.png'),
('MOVIE', 'Final Mission', 'An astronaut''s last mission. A sci-fi drama.', 2022, '14', NULL, 'https://i.imgur.com/backdrop27.png'),
('MOVIE', 'The Experiment', 'A psychological thriller that tests human limits.', 2020, '18', 'https://i.imgur.com/poster28.png', 'https://i.imgur.com/backdrop28.png'),
('MOVIE', 'Family Vacation', 'A heartwarming comedy about a dysfunctional family trip.', 2023, '10', 'https://i.imgur.com/poster29.png', NULL),
('MOVIE', 'Dragon''s Breath', 'A fantasy adventure with knights and dragons.', 2021, '12', 'https://i.imgur.com/poster30.png', 'https://i.imgur.com/backdrop30.png'),
('MOVIE', 'Red Planet', 'A mission to Mars faces a catastrophe. A sci-fi survival story.', 2017, '14', NULL, NULL),
('MOVIE', 'The Getaway', 'A high-octane action movie about a driver for criminals.', 2022, '16', 'https://i.imgur.com/poster32.png', 'https://i.imgur.com/backdrop32.png'),
('MOVIE', 'Jungle Cruise', 'A family adventure deep in the Amazon.', 2021, '10', 'https://i.imgur.com/poster33.png', NULL),
('MOVIE', 'The Institute', 'A mystery thriller about a secret organization.', 2023, '16', 'https://i.imgur.com/poster34.png', 'https://i.imgur.com/backdrop34.png'),
('MOVIE', 'Lost at Sea', 'A drama about a sailor stranded alone.', 2019, '12', NULL, 'https://i.imgur.com/backdrop35.png'),
('MOVIE', 'The Ritual', 'A group of friends encounter an ancient evil. A folk horror.', 2018, '18', 'https://i.imgur.com/poster36.png', 'https://i.imgur.com/backdrop36.png'),
('MOVIE', 'Tomorrow''s War', 'A sci-fi action movie where soldiers from the future recruit in the present.', 2024, '14', 'https://i.imgur.com/poster37.png', NULL),
('MOVIE', 'The Laughing Man', 'A dark drama about a famous comedian.', 2022, '16', 'https://i.imgur.com/poster38.png', 'https://i.imgur.com/backdrop38.png'),
('MOVIE', 'Cupid''s Arrow', 'A lighthearted romantic comedy for Valentine''s day.', 2023, 'L', NULL, NULL),
('MOVIE', 'The Conductor', 'A biography drama of a famous musician.', 2020, '12', 'https://i.imgur.com/poster40.png', 'https://i.imgur.com/backdrop40.png'),
('MOVIE', 'Zombie Apocalypse', 'A standard action horror zombie movie.', 2021, '18', 'https://i.imgur.com/poster41.png', NULL),
('MOVIE', 'The Island', 'A sci-fi mystery where clones discover their true nature.', 2005, '14', 'https://i.imgur.com/poster42.png', 'https://i.imgur.com/backdrop42.png'),
('MOVIE', 'Rogue Agent', 'A spy thriller based on a true story.', 2022, '16', NULL, 'https://i.imgur.com/backdrop43.png'),
('MOVIE', 'Dino Park', 'A sci-fi adventure where dinosaurs are brought back.', 1993, '10', 'https://i.imgur.com/poster44.png', 'https://i.imgur.com/backdrop44.png'),
('MOVIE', 'The Informant', 'A drama about a corporate whistleblower.', 2009, '14', 'https://i.imgur.com/poster45.png', NULL),
('MOVIE', 'Fast Lane', 'An action movie about street racing.', 2023, '14', 'https://i.imgur.com/poster46.png', 'https://i.imgur.com/backdrop46.png'),
('MOVIE', 'The Protector', 'A retired agent must protect his family. Action and drama.', 2021, '16', NULL, NULL),
('MOVIE', 'Echoes of the Past', 'A drama about uncovering family secrets.', 2022, '12', 'https://i.imgur.com/poster48.png', 'https://i.imgur.com/backdrop48.png'),
('MOVIE', 'Galaxy Quest', 'A sci-fi comedy parody.', 1999, '10', 'https://i.imgur.com/poster49.png', NULL),
('MOVIE', 'The Deep House', 'A horror movie set in an underwater haunted house.', 2021, '18', 'https://i.imgur.com/poster50.png', 'https://i.imgur.com/backdrop50.png'),

('SERIES', 'The Crown', 'A historical drama following the reign of Queen Elizabeth II.', 2016, '14', 'https://i.imgur.com/poster51.png', 'https://i.imgur.com/backdrop51.png'),
('SERIES', 'Stranger Things', 'A sci-fi horror series set in the 1980s about a group of kids.', 2016, '16', 'https://i.imgur.com/poster52.png', NULL),
('SERIES', 'The Witcher', 'A fantasy series about a monster hunter, Geralt of Rivia.', 2019, '18', 'https://i.imgur.com/poster53.png', 'https://i.imgur.com/backdrop53.png'),
('SERIES', 'Black Mirror', 'An anthology series exploring the dark side of technology. A sci-fi mystery.', 2011, '18', NULL, 'https://i.imgur.com/backdrop54.png'),
('SERIES', 'Breaking Bad', 'A drama about a chemistry teacher diagnosed with cancer who turns to a life of crime.', 2008, '18', 'https://i.imgur.com/poster55.png', 'https://i.imgur.com/backdrop55.png'),
('SERIES', 'Friends', 'A classic comedy series about six friends living in New York.', 1994, '10', 'https://i.imgur.com/poster56.png', NULL),
('SERIES', 'The Office (US)', 'A mockumentary comedy series about office employees.', 2005, '12', 'https://i.imgur.com/poster57.png', 'https://i.imgur.com/backdrop57.png'),
('SERIES', 'Game of Thrones', 'A fantasy drama series about noble families vying for the Iron Throne.', 2011, '18', 'https://i.imgur.com/poster58.png', NULL),
('SERIES', 'Sherlock', 'A modern update of Sherlock Holmes. A crime mystery.', 2010, '14', 'https://i.imgur.com/poster59.png', 'https://i.imgur.com/backdrop59.png'),
('SERIES', 'Westworld', 'A sci-fi series about a futuristic theme park with androids.', 2016, '18', 'https://i.imgur.com/poster60.png', 'https://i.imgur.com/backdrop60.png'),
('SERIES', 'The Mandalorian', 'A sci-fi western set in the Star Wars universe.', 2019, '12', NULL, 'https://i.imgur.com/backdrop61.png'),
('SERIES', 'Peaky Blinders', 'A historical crime drama set in 1920s England.', 2013, '18', 'https://i.imgur.com/poster62.png', 'https://i.imgur.com/backdrop62.png'),
('SERIES', 'The Queen''s Gambit', 'A drama mini-series about an orphan chess prodigy.', 2020, '16', 'https://i.imgur.com/poster63.png', NULL),
('SERIES', 'Money Heist', 'A Spanish action thriller series about a group of robbers.', 2017, '16', 'https://i.imgur.com/poster64.png', 'https://i.imgur.com/backdrop64.png'),
('SERIES', 'Dark', 'A German sci-fi thriller series involving time travel and family secrets.', 2017, '16', 'https://i.imgur.com/poster65.png', 'https://i.imgur.com/backdrop65.png'),
('SERIES', 'Severance', 'A sci-fi psychological thriller about a workplace experiment.', 2022, '16', NULL, NULL),
('SERIES', 'Ted Lasso', 'A heartwarming comedy series about an American coach in English soccer.', 2020, '12', 'https://i.imgur.com/poster67.png', 'https://i.imgur.com/backdrop67.png'),
('SERIES', 'Arcane', 'An animated fantasy series based on the League of Legends universe.', 2021, '14', 'https://i.imgur.com/poster68.png', NULL),
('SERIES', 'The Boys', 'A dark comedy/action series about corrupt superheroes.', 2019, '18', 'https://i.imgur.com/poster69.png', 'https://i.imgur.com/backdrop69.png'),
('SERIES', 'Succession', 'A drama series about a dysfunctional family that owns a media conglomerate.', 2018, '18', 'https://i.imgur.com/poster70.png', 'https://i.imgur.com/backdrop70.png'),
('SERIES', 'Mindhunter', 'A crime thriller series about the early days of criminal profiling at the FBI.', 2017, '16', NULL, 'https://i.imgur.com/backdrop71.png'),
('SERIES', 'Ozark', 'A crime drama about a financial advisor who launders money.', 2017, '18', 'https://i.imgur.com/poster72.png', 'https://i.imgur.com/backdrop72.png'),
('SERIES', 'Better Call Saul', 'A spin-off drama from Breaking Bad.', 2015, '16', 'https://i.imgur.com/poster73.png', NULL),
('SERIES', 'Narcos', 'A historical crime drama series about the drug trade in Colombia.', 2015, '18', 'https://i.imgur.com/poster74.png', 'https://i.imgur.com/backdrop74.png'),
('SERIES', 'The Haunting of Hill House', 'A supernatural horror drama series.', 2018, '18', 'https://i.imgur.com/poster75.png', 'https://i.imgur.com/backdrop75.png'),
('SERIES', 'Vikings', 'A historical drama series inspired by the sagas of Viking Ragnar Lothbrok.', 2013, '18', NULL, NULL),
('SERIES', 'The Expanse', 'A complex sci-fi series set in a future where humanity has colonized the solar system.', 2015, '16', 'https://i.imgur.com/poster77.png', 'https://i.imgur.com/backdrop77.png'),
('SERIES', 'Loki', 'A sci-fi fantasy series about the Marvel character.', 2021, '12', 'https://i.imgur.com/poster78.png', NULL),
('SERIES', 'Squid Game', 'A South Korean survival drama series.', 2021, '18', 'https://i.imgur.com/poster79.png', 'https://i.imgur.com/backdrop79.png'),
('SERIES', 'Chernobyl', 'A historical drama mini-series about the 1986 nuclear disaster.', 2019, '16', 'https://i.imgur.com/poster80.png', 'https://i.imgur.com/backdrop80.png'),
('SERIES', 'True Detective', 'An anthology crime drama series.', 2014, '18', NULL, 'https://i.imgur.com/backdrop81.png'),
('SERIES', 'The Simpsons', 'A long-running animated comedy series.', 1989, '10', 'https://i.imgur.com/poster82.png', 'https://i.imgur.com/backdrop82.png'),
('SERIES', 'Band of Brothers', 'A war drama mini-series based on WWII.', 2001, '16', 'https://i.imgur.com/poster83.png', NULL),
('SERIES', 'Rick and Morty', 'An adult animated sci-fi comedy series.', 2013, '16', 'https://i.imgur.com/poster84.png', 'https://i.imgur.com/backdrop84.png'),
('SERIES', 'Attack on Titan', 'A dark fantasy anime series.', 2013, '18', 'https://i.imgur.com/poster85.png', 'https://i.imgur.com/backdrop85.png'),
('SERIES', 'Fleabag', 'A dark comedy-drama series.', 2016, '16', NULL, NULL),
('SERIES', 'The Handmaid''s Tale', 'A dystopian drama series.', 2017, '18', 'https://i.imgur.com/poster87.png', 'https://i.imgur.com/backdrop87.png'),
('SERIES', 'Cobra Kai', 'An action-comedy series sequel to The Karate Kid films.', 2018, '12', 'https://i.imgur.com/poster88.png', NULL),
('SERIES', 'Modern Family', 'A mockumentary family comedy series.', 2009, '10', 'https://i.imgur.com/poster89.png', 'https://i.imgur.com/backdrop89.png'),
('SERIES', 'House of the Dragon', 'A fantasy drama prequel to Game of Thrones.', 2022, '18', 'https://i.imgur.com/poster90.png', 'https://i.imgur.com/backdrop90.png'),
('SERIES', 'The Last of Us', 'A post-apocalyptic drama series based on the video game.', 2023, '18', NULL, 'https://i.imgur.com/backdrop91.png'),
('SERIES', 'Yellowstone', 'A modern western drama series.', 2018, '16', 'https://i.imgur.com_poster92.png', 'https://i.imgur.com/backdrop92.png'),
('SERIES', 'Only Murders in the Building', 'A mystery-comedy series.', 2021, '14', 'https://i.imgur.com/poster93.png', NULL),
('SERIES', 'The Sopranos', 'A crime drama series about a mob boss.', 1999, '18', 'https://i.imgur.com/poster94.png', 'https://i.imgur.com/backdrop94.png'),
('SERIES', 'The Wire', 'A crime drama series set in Baltimore.', 2002, '18', 'https://i.imgur.com/poster95.png', 'https://i.imgur.com/backdrop95.png'),
('SERIES', 'Arrested Development', 'A cult comedy series.', 2003, '12', NULL, NULL),
('SERIES', 'Lost', 'A sci-fi mystery series about survivors of a plane crash.', 2004, '14', 'https://i.imgur.com/poster97.png', 'https://i.imgur.com/backdrop97.png'),
('SERIES', 'Dexter', 'A crime drama series about a serial killer who targets other killers.', 2006, '18', 'https://i.imgur.com/poster98.png', NULL),
('SERIES', 'Planet Earth II', 'A breathtaking nature documentary series.', 2016, 'L', 'https://i.imgur.com/poster99.png', 'https://i.imgur.com/backdrop99.png'),
('SERIES', 'Avatar: The Last Airbender', 'A beloved animated fantasy series.', 2005, 'L', 'https://i.imgur.com/poster100.png', 'https://i.imgur.com/backdrop100.png');