INSERT INTO `conteudos` (`titulo`, `descricao`, `ano_lancamento`, `classificacao_indicativa`, `duracao_minutos`, `genero`, `tipo_conteudo`) VALUES

('O Resgate do Soldado Ryan', 'Um grupo de soldados arrisca a vida para salvar um paraquedista atrás das linhas inimigas.', 1998, '16', 169, 'Ação/Guerra', 'FILME'),
('Matrix', 'Um hacker descobre que a realidade é uma simulação criada por máquinas.', 1999, '14', 136, 'Ficção Científica', 'FILME'),
('O Poderoso Chefão', 'O patriarca de uma dinastia do crime organizado transfere o controle para seu filho relutante.', 1972, '18', 175, 'Crime/Drama', 'FILME'),
('A Origem', 'Um ladrão que rouba segredos corporativos através do uso de tecnologia de compartilhamento de sonhos.', 2010, '14', 148, 'Ficção Científica', 'FILME'),
('Interestelar', 'Uma equipe de exploradores viaja através de um buraco de minhoca no espaço.', 2014, '10', 169, 'Ficção Científica', 'FILME'),
('Parasita', 'A família Kim infiltra-se na vida da rica família Park.', 2019, '16', 132, 'Suspense/Drama', 'FILME'),
('Cidade de Deus', 'A ascensão do crime organizado no subúrbio violento do Rio de Janeiro.', 2002, '18', 130, 'Crime/Drama', 'FILME'),
('Vingadores: Ultimato', 'Os Vingadores remanescentes tentam reverter as ações de Thanos.', 2019, '12', 181, 'Ação/Super-herói', 'FILME'),
('Titanic', 'Um aristocrata de dezessete anos se apaixona por um artista pobre a bordo do navio R.M.S. Titanic.', 1997, '12', 195, 'Romance/Drama', 'FILME'),
('O Senhor dos Anéis: O Retorno do Rei', 'Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron.', 2003, '12', 201, 'Fantasia', 'FILME'),
('Pulp Fiction', 'As vidas de dois assassinos da máfia, um boxeador e um par de bandidos se entrelaçam.', 1994, '18', 154, 'Crime/Drama', 'FILME'),
('Forrest Gump', 'As presidências de Kennedy e Johnson, a guerra do Vietnã e outros eventos históricos vistos pelos olhos de um homem do Alabama.', 1994, '12', 142, 'Drama/Romance', 'FILME'),
('Gladiador', 'Um ex-general romano busca vingança contra o imperador corrupto que assassinou sua família.', 2000, '14', 155, 'Ação/Drama', 'FILME'),
('O Rei Leão', 'O príncipe leão Simba e seu pai são alvos de seu tio amargo, que quer ascender ao trono.', 1994, 'L', 88, 'Animação', 'FILME'),
('Toy Story', 'Um boneco caubói se sente ameaçado e ciumento quando uma nova figura de ação espacial o substitui.', 1995, 'L', 81, 'Animação', 'FILME'),

('Breaking Bad', 'Um professor de química com câncer se junta a um ex-aluno para fabricar metanfetamina.', 2008, '18', NULL, 'Crime/Drama', 'SERIE'),
('Game of Thrones', 'Nove famílias nobres lutam pelo controle das terras de Westeros.', 2011, '18', NULL, 'Fantasia/Drama', 'SERIE'),
('Stranger Things', 'Quando um garoto desaparece, sua mãe, um chefe de polícia e seus amigos devem enfrentar forças aterrorizantes.', 2016, '14', NULL, 'Terror/Ficção', 'SERIE'),
('The Office', 'Um mocumentário sobre um grupo de trabalhadores de escritório.', 2005, '12', NULL, 'Comédia', 'SERIE'),
('Friends', 'Segue a vida pessoal e profissional de seis amigos vivendo em Manhattan.', 1994, '12', NULL, 'Comédia/Romance', 'SERIE'),
('Black Mirror', 'Uma série de antologia que explora um mundo distorcido de alta tecnologia.', 2011, '16', NULL, 'Ficção Científica', 'SERIE'),
('The Crown', 'Segue as rivalidades políticas e romances do reinado da Rainha Elizabeth II.', 2016, '14', NULL, 'Drama/Histórico', 'SERIE'),
('Dark', 'Uma saga familiar com uma reviravolta sobrenatural, situada em uma cidade alemã onde o desaparecimento de duas crianças expõe as relações entre quatro famílias.', 2017, '16', NULL, 'Mistério/Sci-Fi', 'SERIE'),
('Mandalorian', 'As viagens de um caçador de recompensas solitário nos confins da galáxia.', 2019, '12', NULL, 'Sci-Fi/Ação', 'SERIE'),
('Sherlock', 'Uma atualização moderna encontra o famoso detetive e seu parceiro doutor resolvendo crimes na Londres do século 21.', 2010, '14', NULL, 'Mistério', 'SERIE'),
('Os Sopranos', 'O chefe da máfia de Nova Jersey, Tony Soprano, lida com questões pessoais e profissionais.', 1999, '18', NULL, 'Crime/Drama', 'SERIE'),
('Arcane', 'Em meio ao conflito entre as cidades-gêmeas de Piltover e Zaun, duas irmãs lutam em lados opostos de uma guerra.', 2021, '14', NULL, 'Animação/Ação', 'SERIE'),
('Narcos', 'Um olhar crônico sobre as façanhas criminosas do traficante colombiano Pablo Escobar.', 2015, '18', NULL, 'Biografia/Crime', 'SERIE'),
('Better Call Saul', 'As provações e tribulações do advogado criminal Jimmy McGill antes de se tornar Saul Goodman.', 2015, '14', NULL, 'Comédia/Crime', 'SERIE'),
('The Boys', 'Um grupo de vigilantes se propõe a derrubar super-heróis corruptos.', 2019, '18', NULL, 'Ação/Comédia', 'SERIE'),
('O Senhor dos Anéis: A Sociedade do Anel', 'Um hobbit manso do Condado e oito companheiros partem em uma jornada para destruir o Um Anel.', 2001, '12', 178, 'Fantasia', 'FILME'),
('O Senhor dos Anéis: As Duas Torres', 'Enquanto Frodo e Sam se aproximam de Mordor com a ajuda de Gollum, a sociedade dividida enfrenta novos inimigos.', 2002, '12', 179, 'Fantasia', 'FILME'),
('Batman: O Cavaleiro das Trevas', 'Quando a ameaça conhecida como Coringa causa estragos em Gotham, Batman deve aceitar um dos maiores testes psicológicos e físicos.', 2008, '12', 152, 'Ação/Crime', 'FILME'),
('A Viagem de Chihiro', 'Durante a mudança de sua família para o subúrbio, uma menina de 10 anos vaga por um mundo governado por deuses, bruxas e espíritos.', 2001, 'L', 125, 'Animação/Fantasia', 'FILME'),
('Clube da Luta', 'Um trabalhador de escritório insone e um fabricante de sabonetes criam um clube de luta clandestino.', 1999, '18', 139, 'Drama', 'FILME'),
('Seven: Os Sete Crimes Capitais', 'Dois detetives, um novato e um veterano, caçam um serial killer que usa os sete pecados capitais como motivos.', 1995, '18', 127, 'Suspense', 'FILME'),
('O Silêncio dos Inocentes', 'Uma jovem cadete do FBI deve receber a ajuda de um assassino canibal encarcerado.', 1991, '18', 118, 'Suspense', 'FILME'),
('Cidade de Deus', 'Dois garotos crescendo em um bairro violento do Rio de Janeiro tomam caminhos diferentes.', 2002, '18', 130, 'Crime/Drama', 'FILME'),
('A Vida é Bela', 'Um bibliotecário judeu usa sua imaginação para proteger seu filho dos horrores de um campo de concentração nazista.', 1997, 'L', 116, 'Comédia/Drama', 'FILME'),
('Os Bons Companheiros', 'A história de Henry Hill e sua vida na máfia, cobrindo seu relacionamento com sua esposa e seus parceiros no crime.', 1990, '18', 146, 'Biografia/Crime', 'FILME'),
('Star Wars: Uma Nova Esperança', 'Luke Skywalker une forças com um cavaleiro Jedi, um piloto arrogante e dois droides para salvar a galáxia.', 1977, 'L', 121, 'Sci-Fi', 'FILME'),
('Star Wars: O Império Contra-Ataca', 'Após a destruição da Estrela da Morte, o Império persegue os Rebeldes.', 1980, 'L', 124, 'Sci-Fi', 'FILME'),
('De Volta para o Futuro', 'Marty McFly é acidentalmente enviado trinta anos para o passado em um DeLorean viajante no tempo.', 1985, 'L', 116, 'Sci-Fi/Comédia', 'FILME'),
('Psicose', 'Uma secretária em fuga rouba $40.000 e faz check-in em um motel remoto administrado por um jovem sob o domínio de sua mãe.', 1960, '14', 109, 'Terror', 'FILME'),
('O Iluminado', 'Uma família se dirige para um hotel isolado para o inverno onde uma presença sinistra influencia o pai.', 1980, '16', 146, 'Terror', 'FILME'),
('WALL-E', 'Em um futuro distante, um pequeno robô coletor de lixo embarca inadvertidamente em uma jornada espacial.', 2008, 'L', 98, 'Animação', 'FILME'),
('Coringa', 'Em Gotham City, o comediante mentalmente perturbado Arthur Fleck é desconsiderado e maltratado pela sociedade.', 2019, '16', 122, 'Crime/Drama', 'FILME'),
('Vingadores: Guerra Infinita', 'Os Vingadores e seus aliados devem estar dispostos a sacrificar tudo para derrotar o poderoso Thanos.', 2018, '12', 149, 'Ação', 'FILME'),
('Homem-Aranha: No Aranhaverso', 'Miles Morales se torna o Homem-Aranha de sua realidade e cruza o caminho com contrapartes de outras dimensões.', 2018, '10', 117, 'Animação', 'FILME'),
('Coco: A Vida é Uma Festa', 'O aspirante a músico Miguel confronta a proibição ancestral de música de sua família entrando na Terra dos Mortos.', 2017, 'L', 105, 'Animação', 'FILME'),
('Whiplash', 'Um jovem baterista promissor matricula-se em um conservatório de música onde seus sonhos de grandeza são mentoreados por um instrutor impiedoso.', 2014, '14', 106, 'Drama', 'FILME'),
('Os Intocáveis', 'Após ficar tetraplégico, um aristocrata contrata um jovem da periferia para ser seu cuidador.', 2011, '12', 112, 'Biografia/Comédia', 'FILME'),
('O Pianista', 'Um músico judeu polonês luta pela sobrevivência na destruição do gueto de Varsóvia na Segunda Guerra Mundial.', 2002, '16', 150, 'Biografia/Drama', 'FILME'),
('Os Infiltrados', 'Um policial disfarçado e uma toupeira na polícia tentam identificar um ao outro enquanto se infiltram em uma gangue irlandesa.', 2006, '18', 151, 'Crime', 'FILME'),
('A Lista de Schindler', 'Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, Oskar Schindler se preocupa com sua força de trabalho judaica.', 1993, '14', 195, 'Biografia/Histórico', 'FILME'),
('Duna', 'Adaptação do romance de ficção científica sobre o filho de uma família nobre encarregado de proteger o elemento mais vital da galáxia.', 2021, '14', 155, 'Sci-Fi', 'FILME'),
('Top Gun: Maverick', 'Depois de mais de 30 anos de serviço, Pete Mitchell está onde pertence, ultrapassando os limites como piloto de teste.', 2022, '12', 130, 'Ação', 'FILME'),
('Tudo em Todo o Lugar ao Mesmo Tempo', 'Uma imigrante chinesa idosa é envolvida em uma aventura insana, onde ela sozinha pode salvar o mundo explorando outros universos.', 2022, '14', 139, 'Ação/Comédia', 'FILME'),
('Avatar', 'Um fuzileiro naval paraplégico despachado para a lua Pandora em uma missão única fica dividido entre seguir suas ordens e proteger o mundo.', 2009, '12', 162, 'Sci-Fi', 'FILME'),
('Harry Potter e a Pedra Filosofal', 'Um garoto órfão se matricula em uma escola de magia e bruxaria.', 2001, 'L', 152, 'Fantasia', 'FILME'),
('Harry Potter e as Relíquias da Morte: Parte 2', 'Harry, Ron e Hermione procuram as Horcruxes restantes de Voldemort em seu esforço para destruir o Lorde das Trevas.', 2011, '12', 130, 'Fantasia', 'FILME'),
('Pantera Negra', 'T\'Challa, herdeiro do reino oculto de Wakanda, deve liderar seu povo para um novo futuro.', 2018, '12', 134, 'Ação', 'FILME'),
('Jurassic Park', 'Um parque temático sofrido uma falha de segurança permite que seus clones de dinossauros corram soltos.', 1993, '10', 127, 'Aventura', 'FILME'),
('Indiana Jones e os Caçadores da Arca Perdida', 'O arqueólogo aventureiro Indiana Jones corre contra o tempo para recuperar uma relíquia bíblica.', 1981, '12', 115, 'Aventura', 'FILME'),
('Rocky: Um Lutador', 'Um boxeador de classe trabalhadora da Filadélfia recebe uma chance única de lutar contra o campeão mundial.', 1976, '12', 120, 'Drama/Esporte', 'FILME'),

('The Last of Us', 'Após uma pandemia global destruir a civilização, um sobrevivente endurecido toma conta de uma garota de 14 anos.', 2023, '16', NULL, 'Drama/Terror', 'SERIE'),
('Succession', 'A saga de uma família americana proprietária de um império de mídia global.', 2018, '16', NULL, 'Drama', 'SERIE'),
('The Office (UK)', 'Acompanha o dia a dia dos funcionários de um escritório em Slough.', 2001, '14', NULL, 'Comédia', 'SERIE'),
('Peaky Blinders', 'Uma gangue familiar em Birmingham, Inglaterra, em 1919.', 2013, '18', NULL, 'Crime/Drama', 'SERIE'),
('Vikings', 'Vikings nos transporta para o mundo brutal e misterioso de Ragnar Lothbrok.', 2013, '16', NULL, 'Ação/Histórico', 'SERIE'),
('The Witcher', 'Geralt de Rívia, um caçador de monstros mutante, viaja em direção ao seu destino em um mundo turbulento.', 2019, '16', NULL, 'Fantasia', 'SERIE'),
('Round 6', 'Centenas de jogadores falidos aceitam um estranho convite para competir em jogos infantis.', 2021, '18', NULL, 'Suspense', 'SERIE'),
('La Casa de Papel', 'Um grupo inusitado de ladrões tenta realizar o roubo mais perfeito da história da Espanha.', 2017, '16', NULL, 'Crime/Ação', 'SERIE'),
('Chernobyl', 'Em abril de 1986, uma explosão na usina nuclear de Chernobyl se torna uma das piores catástrofes causadas pelo homem.', 2019, '14', NULL, 'Drama/Histórico', 'SERIE'),
('Band of Brothers', 'A história da Easy Company do Exército dos EUA durante a Segunda Guerra Mundial.', 2001, '16', NULL, 'Guerra', 'SERIE'),
('Rick and Morty', 'As aventuras de um cientista sociopata e seu neto.', 2013, '16', NULL, 'Animação/Sci-Fi', 'SERIE'),
('BoJack Horseman', 'Um cavalo humanoide, estrela de sitcom dos anos 90, tenta recuperar sua fama.', 2014, '16', NULL, 'Animação/Comédia', 'SERIE'),
('Avatar: A Lenda de Aang', 'Em um mundo devastado pela guerra, um garoto pode manipular os elementos.', 2005, 'L', NULL, 'Animação', 'SERIE'),
('One Piece', 'Monkey D. Luffy navega com sua tripulação de piratas em busca do tesouro One Piece.', 1999, '12', NULL, 'Anime', 'SERIE'),
('Naruto Shippuden', 'Naruto Uzumaki busca se tornar o líder de sua vila, o Hokage.', 2007, '12', NULL, 'Anime', 'SERIE'),
('Attack on Titan', 'A humanidade vive em cidades cercadas por enormes muralhas que os protegem de titãs.', 2013, '16', NULL, 'Anime', 'SERIE'),
('Fullmetal Alchemist: Brotherhood', 'Dois irmãos procuram a Pedra Filosofal após uma tentativa fracassada de reviver sua mãe.', 2009, '14', NULL, 'Anime', 'SERIE'),
('Death Note', 'Um estudante do ensino médio descobre um caderno sobrenatural que lhe permite matar qualquer pessoa.', 2006, '14', NULL, 'Anime', 'SERIE'),
('Cowboy Bebop', 'As aventuras futuristas de um caçador de recompensas e seus parceiros.', 1998, '14', NULL, 'Anime', 'SERIE'),
('Friends', 'Acompanha a vida pessoal e profissional de seis amigos vivendo em Manhattan.', 1994, '12', NULL, 'Comédia', 'SERIE'),
('How I Met Your Mother', 'Um pai conta a seus filhos a jornada de como ele conheceu a mãe deles.', 2005, '12', NULL, 'Comédia', 'SERIE'),
('Brooklyn Nine-Nine', 'Acompanha as aventuras de um detetive imaturo e seus colegas em uma delegacia de NY.', 2013, '12', NULL, 'Comédia', 'SERIE'),
('Modern Family', 'Três famílias diferentes, mas relacionadas, enfrentam provações e tribulações de suas próprias formas.', 2009, '10', NULL, 'Comédia', 'SERIE'),
('Grey\'s Anatomy', 'Um drama centrado na vida pessoal e profissional de cinco estagiários cirúrgicos e seus supervisores.', 2005, '14', NULL, 'Drama', 'SERIE'),
('House', 'Um médico dissidente e antissocial se especializa em medicina diagnóstica.', 2004, '14', NULL, 'Drama', 'SERIE'),
('The Good Doctor', 'Um jovem cirurgião com autismo e síndrome de savant é recrutado para a unidade cirúrgica pediátrica.', 2017, '12', NULL, 'Drama', 'SERIE'),
('Dexter', 'Um especialista forense de Miami vive uma vida dupla como serial killer de criminosos.', 2006, '18', NULL, 'Crime/Drama', 'SERIE'),
('Hannibal', 'Explora o relacionamento inicial entre o psiquiatra Hannibal Lecter e um jovem perfilador do FBI.', 2013, '18', NULL, 'Terror/Policial', 'SERIE'),
('True Detective', 'Série antológica em que investigações policiais desvendam os segredos pessoais e profissionais dos envolvidos.', 2014, '18', NULL, 'Crime/Drama', 'SERIE'),
('Fargo', 'Várias crônicas de decepção, intriga e assassinato na gelada Minnesota.', 2014, '16', NULL, 'Crime/Comédia', 'SERIE'),
('Westworld', 'Em um parque temático futurista, os anfitriões andróides começam a desviar de seus roteiros.', 2016, '18', NULL, 'Sci-Fi', 'SERIE'),
('Lost', 'Os sobreviventes de um acidente de avião são forçados a trabalhar juntos para sobreviver em uma ilha tropical deserta.', 2004, '14', NULL, 'Aventura/Drama', 'SERIE'),
('Walking Dead', 'O xerife Rick Grimes acorda de um coma para descobrir que o mundo está em ruínas devido a um apocalipse zumbi.', 2010, '16', NULL, 'Terror', 'SERIE'),
('Supernatural', 'Dois irmãos seguem os passos do pai como caçadores, lutando contra seres sobrenaturais.', 2005, '14', NULL, 'Fantasia/Terror', 'SERIE'),
('Doctor Who', 'As aventuras do Doutor, um Senhor do Tempo alienígena que viaja pelo universo em sua TARDIS.', 2005, '10', NULL, 'Sci-Fi', 'SERIE');