INSERT INTO `perfis` (`id_usuario`, `nome_perfil`, `avatar_url`, `tipo_perfil`) VALUES

(1, 'Lucas', 'avatar_01.png', 'ADULTO'),
(2, 'Mariana', 'avatar_02.png', 'ADULTO'),
(3, 'Pedro', 'avatar_03.png', 'ADULTO'),
(3, 'Pedro Jr', 'avatar_kids_01.png', 'INFANTIL'), 
(4, 'Ana', 'avatar_04.png', 'ADULTO'),
(5, 'Carlos', 'avatar_05.png', 'ADULTO'),
(6, 'Fernanda', 'avatar_06.png', 'ADULTO'),
(7, 'João', 'avatar_07.png', 'ADULTO'),
(8, 'Beatriz', 'avatar_08.png', 'ADULTO'),
(9, 'Gabriel', 'avatar_09.png', 'ADULTO'),
(9, 'Biel', 'avatar_10.png', 'ADULTO'), 
(9, 'Criança', 'avatar_kids_02.png', 'INFANTIL'), 
(10, 'Larissa', 'avatar_11.png', 'ADULTO'),
(11, 'Rafael', 'avatar_12.png', 'ADULTO'),
(12, 'Camila', 'avatar_13.png', 'ADULTO'),
(13, 'Gustavo', 'avatar_14.png', 'ADULTO'),
(14, 'Juliana', 'avatar_15.png', 'ADULTO'),
(15, 'Bruno', 'avatar_16.png', 'ADULTO'),
(15, 'Família Bruno', 'avatar_17.png', 'ADULTO'), 
(16, 'Amanda', 'avatar_18.png', 'ADULTO'),
(17, 'Rodrigo', 'avatar_19.png', 'ADULTO'),
(18, 'Patrícia', 'avatar_20.png', 'ADULTO'),
(19, 'Thiago', 'avatar_21.png', 'ADULTO'),
(19, 'Thiago Kids', 'avatar_kids_03.png', 'INFANTIL'), 
(20, 'Vanessa', 'avatar_22.png', 'ADULTO'),
(21, 'Felipe', 'avatar_23.png', 'ADULTO'),
(22, 'Jessica', 'avatar_24.png', 'ADULTO'),
(23, 'André', 'avatar_25.png', 'ADULTO'),
(24, 'Laura', 'avatar_26.png', 'ADULTO'),
(24, 'Visitante', 'avatar_default.png', 'ADULTO'), 
(25, 'Daniel', 'avatar_27.png', 'ADULTO'),
(26, 'Tatiana', 'avatar_28.png', 'ADULTO'),
(27, 'Eduardo', 'avatar_29.png', 'ADULTO'),
(28, 'Renata', 'avatar_30.png', 'ADULTO'),
(29, 'Leonardo', 'avatar_31.png', 'ADULTO'),
(29, 'Leo Games', 'avatar_32.png', 'ADULTO'), 
(30, 'Cláudia', 'avatar_33.png', 'ADULTO'),
(31, 'Marcelo', 'avatar_34.png', 'ADULTO'),
(32, 'Alice', 'avatar_35.png', 'ADULTO'),
(33, 'Vitor', 'avatar_36.png', 'ADULTO'),
(34, 'Isabela', 'avatar_37.png', 'ADULTO'),
(35, 'Ricardo', 'avatar_38.png', 'ADULTO'),
(36, 'Monique', 'avatar_39.png', 'ADULTO'),
(37, 'Sérgio', 'avatar_40.png', 'ADULTO'),
(38, 'Helena', 'avatar_41.png', 'ADULTO'),
(39, 'Caio', 'avatar_42.png', 'ADULTO'),
(39, 'Caio Kids', 'avatar_kids_04.png', 'INFANTIL'), 
(40, 'Luana', 'avatar_43.png', 'ADULTO'),
(41, 'Jorge', 'avatar_44.png', 'ADULTO'),
(42, 'Priscila', 'avatar_45.png', 'ADULTO'),
(43, 'Matheus', 'avatar_46.png', 'ADULTO'),
(44, 'Débora', 'avatar_47.png', 'ADULTO'),
(45, 'Alexandre', 'avatar_48.png', 'ADULTO'),
(46, 'Bianca', 'avatar_49.png', 'ADULTO'),
(47, 'Roberto', 'avatar_50.png', 'ADULTO'),
(48, 'Natalia', 'avatar_51.png', 'ADULTO'),
(49, 'Fábio', 'avatar_52.png', 'ADULTO'),
(49, 'Fabinho', 'avatar_kids_05.png', 'INFANTIL'), 
(50, 'Leticia', 'avatar_53.png', 'ADULTO'),
(51, 'Fernando', 'avatar_54.png', 'ADULTO'),
(52, 'Cecília', 'avatar_55.png', 'ADULTO'),
(53, 'Henrique', 'avatar_56.png', 'ADULTO'),
(54, 'Carolina', 'avatar_57.png', 'ADULTO'),
(54, 'Carol', 'avatar_58.png', 'ADULTO'), 
(55, 'Diogo', 'avatar_59.png', 'ADULTO'),
(56, 'Elaine', 'avatar_60.png', 'ADULTO'),
(57, 'Vinícius', 'avatar_61.png', 'ADULTO'),
(58, 'Sofia', 'avatar_62.png', 'ADULTO'),
(59, 'Lucas V.', 'avatar_63.png', 'ADULTO'),
(59, 'Lucas Jr', 'avatar_kids_06.png', 'INFANTIL'), 
(60, 'Marcela', 'avatar_64.png', 'ADULTO'),
(61, 'Guilherme', 'avatar_65.png', 'ADULTO'),
(62, 'Raquel', 'avatar_66.png', 'ADULTO'),
(63, 'Samuel', 'avatar_67.png', 'ADULTO'),
(64, 'Lorena', 'avatar_68.png', 'ADULTO'),
(64, 'Lorena Work', 'avatar_69.png', 'ADULTO'), 
(65, 'Otávio', 'avatar_70.png', 'ADULTO'),
(66, 'Talita', 'avatar_71.png', 'ADULTO'),
(67, 'Murilo', 'avatar_72.png', 'ADULTO'),
(68, 'Joana', 'avatar_73.png', 'ADULTO'),
(69, 'Arthur', 'avatar_74.png', 'ADULTO'),
(69, 'Arthur Filho', 'avatar_kids_07.png', 'INFANTIL'), 
(70, 'Milena', 'avatar_75.png', 'ADULTO'),
(71, 'Igor', 'avatar_76.png', 'ADULTO'),
(72, 'Sabrina', 'avatar_77.png', 'ADULTO'),
(73, 'Renan', 'avatar_78.png', 'ADULTO'),
(74, 'Evelyn', 'avatar_79.png', 'ADULTO'),
(74, 'Evelyn 2', 'avatar_80.png', 'ADULTO'), 
(75, 'Leandro', 'avatar_81.png', 'ADULTO'),
(76, 'Yasmin', 'avatar_82.png', 'ADULTO'),
(77, 'Douglas', 'avatar_83.png', 'ADULTO'),
(78, 'Livia', 'avatar_84.png', 'ADULTO'),
(79, 'Marco', 'avatar_85.png', 'ADULTO'),
(79, 'Marquinho', 'avatar_kids_08.png', 'INFANTIL'), 
(80, 'Tainá', 'avatar_86.png', 'ADULTO'),
(81, 'César', 'avatar_87.png', 'ADULTO'),
(82, 'Brenda', 'avatar_88.png', 'ADULTO'),
(83, 'Willian', 'avatar_89.png', 'ADULTO'),
(84, 'Clara', 'avatar_90.png', 'ADULTO'),
(84, 'Pais', 'avatar_91.png', 'ADULTO'), 
(84, 'Filhos', 'avatar_kids_09.png', 'INFANTIL'), 
(85, 'Elias', 'avatar_92.png', 'ADULTO'),
(86, 'Flávia', 'avatar_93.png', 'ADULTO'),
(87, 'Rogério', 'avatar_94.png', 'ADULTO'),
(88, 'Sarah', 'avatar_95.png', 'ADULTO'),
(89, 'Francisco', 'avatar_96.png', 'ADULTO'),
(89, 'Chico', 'avatar_97.png', 'ADULTO'), 
(90, 'Gisele', 'avatar_98.png', 'ADULTO'),
(91, 'Márcio', 'avatar_99.png', 'ADULTO'),
(92, 'Vitória', 'avatar_100.png', 'ADULTO'),
(93, 'Tiago', 'avatar_101.png', 'ADULTO'),
(94, 'Elisa', 'avatar_102.png', 'ADULTO'),
(94, 'Bebê', 'avatar_kids_10.png', 'INFANTIL'), 
(95, 'Luiz', 'avatar_103.png', 'ADULTO'),
(96, 'Bárbara', 'avatar_104.png', 'ADULTO'),
(97, 'Victor', 'avatar_105.png', 'ADULTO'),
(98, 'Aline', 'avatar_106.png', 'ADULTO'),
(99, 'José', 'avatar_107.png', 'ADULTO'),
(99, 'Zé', 'avatar_108.png', 'ADULTO'), 
(100, 'Cristina', 'avatar_109.png', 'ADULTO');